In [ ]:
#Poland part
import pandas as pd
from pathlib import Path

p = Path('.')

files = [p / f"{year}_Poland.json" for year in range(2020, 2026)]

dfs = []
for f in files:
    j = pd.read_json(f, orient='records')
    if isinstance(j, pd.DataFrame) and j.empty:
        import json
        with open(f, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
        for key in ('dataset', 'results', 'data', 'items'):
            if key in data and isinstance(data[key], list):
                j = pd.DataFrame(data[key])
                break
        else:
            if isinstance(data, list):
                j = pd.DataFrame(data)
            else:
                j = pd.DataFrame([data])
    dfs.append(j)

df = pd.concat(dfs, ignore_index=True, sort=False)

if 'year' not in df.columns:
    years = []
    for f in files:
        try:
            years.append(int(f.stem.split('_')[0]))
        except:
            years.append(None)
    blocks = [len(d) for d in dfs]
    year_col = []
    for y, cnt in zip(years, blocks):
        year_col += [y] * cnt
    if len(year_col) == len(df):
        df['year'] = year_col

print(df.shape)
df.to_csv('Poland_2020_2025_combined.csv', index=False, encoding='utf-8')

(135, 48)

In [3]:
df_poland = pd.read_csv("Poland_2020_2025_combined.csv")
df_poland.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,year
0,C,A,20200101,2020,52,2020,40,AUT,Austria,X,...,False,0,False,0.0,13134.033,13134.033,0,True,False,2020
1,C,A,20200101,2020,52,2020,56,BEL,Belgium,X,...,False,0,False,NaN,931073.245,931073.245,0,True,False,2020
2,C,A,20200101,2020,52,2020,76,BRA,Brazil,X,...,False,0,False,NaN,107.000,107.000,0,False,True,2020
3,C,A,20200101,2020,52,2020,100,BGR,Bulgaria,X,...,False,0,False,0.0,19787.531,19787.531,0,False,True,2020
4,C,A,20200101,2020,52,2020,203,CZE,Czechia,X,...,False,0,False,0.0,31153.000,31153.000,0,False,True,2020

In [ ]:
df_poland.columns.unique()

Index(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period',
       'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate', 'year'],
      dtype='str')

In [9]:
df_poland.partnerDesc.unique()

<StringArray>
['Poland']
Length: 1, dtype: str

In [5]:
df_poland.reporterDesc.unique()

<StringArray>
[        'Austria',         'Belgium',          'Brazil',        'Bulgaria',
         'Czechia',          'France',         'Germany',          'Greece',
         'Hungary',          'Israel',           'Italy',       'Lithuania',
         'Morocco',     'Netherlands',        'Portugal',         'Romania',
           'Spain',         'Tunisia',         'Türkiye',         'Ukraine',
 'North Macedonia',  'United Kingdom',      'Uzbekistan',         'Croatia',
         'Denmark',            'Iran',          'Latvia',         'Namibia',
           'India',        'Slovakia',          'Sweden',           'Egypt',
             'USA',          'Serbia',          'Jordan',        'Slovenia',
         'Estonia',          'Norway']
Length: 38, dtype: str

In [6]:
df_poland.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [7]:
#UK part
import pandas as pd
from pathlib import Path

p = Path('.')

files = [p / f"{year}_UK.json" for year in range(2020, 2026)]

dfs = []
for f in files:
    j = pd.read_json(f, orient='records')
    if isinstance(j, pd.DataFrame) and j.empty:
        import json
        with open(f, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
        for key in ('dataset', 'results', 'data', 'items'):
            if key in data and isinstance(data[key], list):
                j = pd.DataFrame(data[key])
                break
        else:
            if isinstance(data, list):
                j = pd.DataFrame(data)
            else:
                j = pd.DataFrame([data])
    dfs.append(j)

df = pd.concat(dfs, ignore_index=True, sort=False)

if 'year' not in df.columns:
    years = []
    for f in files:
        try:
            years.append(int(f.stem.split('_')[0]))
        except:
            years.append(None)
    blocks = [len(d) for d in dfs]
    year_col = []
    for y, cnt in zip(years, blocks):
        year_col += [y] * cnt
    if len(year_col) == len(df):
        df['year'] = year_col

print(df.shape)
df.to_csv('UK_2020_2025_combined.csv', index=False, encoding='utf-8')

(216, 48)

In [8]:
df_uk = pd.read_csv("UK_2020_2025_combined.csv")
df_uk.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,year
0,C,A,20200101,2020,52,2020,24,AGO,Angola,X,...,False,0,False,NaN,8.505,8.505,0,False,True,2020
1,C,A,20200101,2020,52,2020,40,AUT,Austria,X,...,False,0,False,0.0,59.420,59.420,0,True,False,2020
2,C,A,20200101,2020,52,2020,56,BEL,Belgium,X,...,False,0,False,NaN,7245039.781,7245039.781,0,True,False,2020
3,C,A,20200101,2020,52,2020,76,BRA,Brazil,X,...,False,0,False,NaN,35566.000,35566.000,0,False,True,2020
4,C,A,20200101,2020,52,2020,100,BGR,Bulgaria,X,...,False,0,False,0.0,627139.827,627139.827,0,False,True,2020

In [10]:
df_uk.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [11]:
df_uk.partnerDesc.unique()

<StringArray>
['United Kingdom']
Length: 1, dtype: str

In [14]:
#Germany part
import pandas as pd
from pathlib import Path

p = Path('.')

files = [p / f"{year}_Germnany.json" for year in range(2020, 2026)]

dfs = []
for f in files:
    j = pd.read_json(f, orient='records')
    if isinstance(j, pd.DataFrame) and j.empty:
        import json
        with open(f, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
        for key in ('dataset', 'results', 'data', 'items'):
            if key in data and isinstance(data[key], list):
                j = pd.DataFrame(data[key])
                break
        else:
            if isinstance(data, list):
                j = pd.DataFrame(data)
            else:
                j = pd.DataFrame([data])
    dfs.append(j)

df = pd.concat(dfs, ignore_index=True, sort=False)

if 'year' not in df.columns:
    years = []
    for f in files:
        try:
            years.append(int(f.stem.split('_')[0]))
        except:
            years.append(None)
    blocks = [len(d) for d in dfs]
    year_col = []
    for y, cnt in zip(years, blocks):
        year_col += [y] * cnt
    if len(year_col) == len(df):
        df['year'] = year_col

print(df.shape)
df.to_csv('Germany_2020_2025_combined.csv', index=False, encoding='utf-8')

(462, 48)

In [15]:
df_ge = pd.read_csv("Germany_2020_2025_combined.csv")
df_ge.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,year
0,C,A,20200101,2020,52,2020,8,ALB,Albania,X,...,False,0,False,0.0,1.332623e+05,1.332623e+05,0,False,True,2020
1,C,A,20200101,2020,52,2020,24,AGO,Angola,X,...,False,0,False,NaN,4.091800e+01,4.091800e+01,0,False,True,2020
2,C,A,20200101,2020,52,2020,40,AUT,Austria,X,...,False,0,False,0.0,3.636547e+06,3.636547e+06,0,True,False,2020
3,C,A,20200101,2020,52,2020,56,BEL,Belgium,X,...,False,0,False,NaN,1.037082e+07,1.037082e+07,0,True,False,2020
4,C,A,20200101,2020,52,2020,70,BIH,Bosnia Herzegovina,X,...,False,0,False,NaN,3.091627e+04,3.091627e+04,0,False,True,2020

In [16]:
df_ge.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [17]:
df_ge.partnerDesc.unique()

<StringArray>
['Germany']
Length: 1, dtype: str

In [21]:
#making general dataframe
hot_df = pd.concat([df_poland, df_uk, df_ge], ignore_index=True, sort=False)
hot_df.to_csv('Poland_UK_Germany_2020_2025_combined.csv', index=False, encoding='utf-8')
hot_df = pd.read_csv('Poland_UK_Germany_2020_2025_combined.csv')
hot_df.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,year
0,C,A,20200101,2020,52,2020,40,AUT,Austria,X,...,False,0,False,0.0,13134.033,13134.033,0,True,False,2020
1,C,A,20200101,2020,52,2020,56,BEL,Belgium,X,...,False,0,False,NaN,931073.245,931073.245,0,True,False,2020
2,C,A,20200101,2020,52,2020,76,BRA,Brazil,X,...,False,0,False,NaN,107.000,107.000,0,False,True,2020
3,C,A,20200101,2020,52,2020,100,BGR,Bulgaria,X,...,False,0,False,0.0,19787.531,19787.531,0,False,True,2020
4,C,A,20200101,2020,52,2020,203,CZE,Czechia,X,...,False,0,False,0.0,31153.000,31153.000,0,False,True,2020

In [25]:
hot_df.qty.head(5)

0      6950.0
1    548869.0
2       134.0
3     10970.0
4     17836.0
Name: qty, dtype: float64

In [36]:
#Find general kg AND money value for Partner country

agg = hot_df.groupby('partnerDesc', dropna=True).agg(
    sum_fobvalue=pd.NamedAgg(column='fobvalue', aggfunc='sum'),
    sum_qty=pd.NamedAgg(column='qty', aggfunc='sum')
).reset_index()

agg['sum_fobvalue_fmt'] = agg['sum_fobvalue'].map(lambda x: f"{x:.2f}")
agg['sum_qty_fmt'] = agg['sum_qty'].map(lambda x: f"{x:.2f}")

result_df = agg[['partnerDesc', 'sum_fobvalue_fmt', 'sum_qty_fmt']].rename(
    columns={
        'partnerDesc': 'Import Country',
        'sum_fobvalue_fmt': 'Total_USD',
        'sum_qty_fmt': 'Total_Qty_kg'
    }
)

print(result_df)

   Import Country        Total_USD   Total_Qty_kg
0         Germany  886568877091.45  1483941545.07
1          Poland     801458734.51   414845764.79
2  United Kingdom    3024365719.37  1341327213.25

In [41]:
#Find general kg AND money value for Reporter country
agg = hot_df.groupby('reporterDesc', dropna=True).agg(
    sum_fobvalue=pd.NamedAgg(column='fobvalue', aggfunc='sum'),
    sum_qty=pd.NamedAgg(column='qty', aggfunc='sum')
).reset_index()

agg = agg[agg['sum_fobvalue'] != 0].reset_index()

agg['sum_fobvalue_fmt'] = agg['sum_fobvalue'].map(lambda x: f"{x:.2f}")
agg['sum_qty_fmt'] = agg['sum_qty'].map(lambda x: f"{x:.2f}")

result_df = agg[['reporterDesc', 'sum_fobvalue_fmt', 'sum_qty_fmt']].rename(
    columns={
        'reporterDesc': 'Import Country',
        'sum_fobvalue_fmt': 'Total_USD',
        'sum_qty_fmt': 'Total_Qty_kg'
    }
)

print(result_df)

             Import Country       Total_USD Total_Qty_kg
0                   Albania       253250.85    235173.20
1                    Angola    342481198.69       364.00
2                 Argentina   5235043677.92         0.00
3                 Australia  35340852271.93         0.00
4                   Austria     23070945.18  11046281.00
..                      ...             ...          ...
92  United Rep. of Tanzania    196452373.95     24961.80
93                  Uruguay    272665700.55     17886.52
94               Uzbekistan         6066.00     15040.00
95                 Viet Nam       140238.01     69252.36
96                   Zambia      8678243.46         0.00

[97 rows x 3 columns]

In [44]:
result_df.to_excel('Export Countries.xlsx', index=False,)